CREATE DATABASE CompanyDB;
USE CompanyDB;
-- CREATE TABLE A(B INT);
-- drop TABLE A;
CREATE TABLE Employee 
	( EMPID INTEGER, EMPNAME TEXT, DESIGNATION CHAR,
	  SALARY INTEGER, PROVIDANT_FUND INTEGER);
INSERT INTO Employee VALUES (1,"HAMMAD","f",100000000,99999999);
SELECT *,SALARY*0.17,SALARY*0.17+PROVIDANT_FUND,SALARY-SALARY*0.17 FROM Employee;
-- SHOW COLUMN FROM CompanyDB;

-- to delete database
-- DROP DATABASE CompanyDB;